---
- name: Set System Banners
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Configure the MOTD login banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          *********************************
          ***    Welcome To My Network  ***
          ***       Do not break it!    ***
          ***           Cheers          ***
          *********************************
        state: present   
...