---
- name: Basic Device Configuration
  hosts: LAB-HOSTS
  connection: local
  gather_facts: no

  tasks:

  - name: Configure Global Settings
    ios_config:
      commands:
        - snmp-server community ansible-public-string RO
        - snmp-server community ansible-private-string RW
        - ip domain name pjw.network
        - no ip domain lookup
        - no ip http server

  - name: Configure VTY Settings
    ios_config:
      lines:
        - transport input ssh
        - exec-timeout 120
      parents: line vty 0 4

  - name: Configure the login banner
    cisco.ios.ios_banner:
      banner: motd
      text: |
          ****************************************
          ****    Welcome To The Lab Network  ****
          ****       Do not break it!         ****
          ****           Cheers               ****
          ****                                ****
          ****  --Base Config v1.0            ****
          ****************************************
      state: present   
    
  - name: save running to startup when modified
    cisco.ios.ios_config:
      save_when: modified