---
- name: Gather IOS Facts
  hosts: LAB-HOSTS
  gather_facts: no
  connection: local
  tasks:
    - name: Gather IOS Facts
      ios_facts:

    - name: What is the IOS OS ver?
      debug:
        var: ansible_net_version

    - name: What is the hostname?
      debug:
        var: ansible_net_hostname

    - name: What is the hostname?
      debug:
        var: ansible_net_interfaces

...
