---
- name: Add L3 Interfaces
  hosts: LAN
  gather_facts: no
  connection: local

  tasks:
  - name: Add vlan 100
    cisco.ios.ios_l3_interfaces:
      config:
      - name: vlan100
        ipv4:
        - address: 192.168.100.1/24
      state: merged
...
